### PR TITLE
Fixes #4.  Fix DST start/end month.  Calculate DST from ordinal week number.

### LINKED ISSUE #4: DST calculation issues
A couple of issues with daylight savings calculations:

1) In lines 301 and 302, dst() is passing dt[1] as the month argument to day_from_week_and_weekday().  This is the current month, but I believe it should instead be passing the months from _dst_start and _dst_end.

2) The method of specifying DST start/end is by ordinal week number and day of week.  This doesn't match national specifications for DST which refer to ordinal days of week in the month, which is not the same.  For example, USA says DST ends on the first Sunday in November, but if I specify with set_dst_end() the Sunday in the first week in November, day_from_week_and_weekday() will raise an exception because the first week of November 2023 does not include a Sunday.

I have written a substitute function for day_from_week_and_weekday() which calculates from ordinal weekdays that I can put in a pull request if you are interested.

### PR DESCRIPTION
**Pull request by ecwilliams**

### CODE REVIEW

**Review by ekondayan — CHANGES_REQUESTED** [review]
1. Would you change the docstring as in the attached file 
[week_in_month.txt](https://github.com/ekondayan/micropython-ntp/files/12775339/week_in_month.txt)
2. Would you change the formatting on lines 877 and 878 by putting spaces around the + and - operators.
3. In the commit message, would you explain why this change is necessary and what it fixes.

Thank you.

**Comment by ecwilliams** [comment]
Is that docstring intended for day_from_week_and_weekday() or for
weekday_in_month() ?

The examples in the docstring imply the former, but that function is not my
code.

**Comment by ekondayan** [comment]
Sorry for the oversight, I took the example section from the "day_from_week_and_weekday" and forgot to change the name.  Everything else is related to your function("weekday_in_month"). If you see something inaccurate feel free to edit it as you wish.
[weekday_in_month.txt](https://github.com/ekondayan/micropython-ntp/files/12839849/weekday_in_month.txt)

One more thing, would you rename the "ordinal" argument to "ordinal_week"

Thank you.

**Comment by ecwilliams** [comment]
"ordinal_week" isn't the correct meaning for that parameter, this was part
of the problem in the day_from_week_and_weekday() code that I was fixing.
It's the Nth weekday in that month, so maybe ordinal_weekday?

**Comment by ekondayan** [comment]
Yes, it is better

**Comment by ecwilliams** [comment]
Should WEEK_FORTH be WEEK_FOURTH?

**Comment by ekondayan** [comment]
Yes

**Comment by ecwilliams** [comment]
Amended and pushed.

**Comment by ekondayan** [comment]
Thanks for the contribution. One last thing before I merge the commit.
Would you explain in the commit description why "Calculate DST from ordinal week number" is introduced and why is it needed.

**Comment by ecwilliams** [comment]
Not sure I understand what you're asking me to explain.  "Calculate DST
from ordinal week number" is what day_from_week_and_weekday() is already
doing.

It's doing that wrong in some cases.  But, more importantly, it's solving
the wrong problem:  Correct me if I'm wrong, but no country I've found so
far defines DST transition days in those terms.

**Comment by ekondayan** [comment]
> Not sure I understand what you're asking me to explain.  "Calculate DST
from ordinal week number" is what day_from_week_and_weekday() is already
doing.

day_from_week_and_weekday() is perfectly fit to find the last weekday of the month, which is applicable to half the countries that use DST. The shortcoming is that it does not work for the countries that change the DST on a day other than the last weekday of the month. Take a look at [DST by country](https://en.wikipedia.org/wiki/Daylight_saving_time_by_country)

The correct way is to find the ordinal weekday of the month, which weekday_in_month() is doing.

I am asking you to explain that in the commit message, so when people pull that commit, they can see the reason behind switching from day_from_week_and_weekday() to weekday_in_month().

I believe that for a project to be successful I must be very well commented and explained. That is why I am asking you to verbosely explain your PR in the docstring of the function and the commit message. 

P.S. 
Now I see one country that the library does not support - Israel. They change the time on the Friday before the last Sunday :)

**Comment by ekondayan** [comment]
You can confirm that both functions find the last weekday correctly

```python
import unittest
import ntp


class TestDayFromWeekAndWeekdayWithImport(unittest.TestCase):

    def test_compare_both(self):
        errors = []
        for year in range(1, 3000):
            for month in range(ntp.Ntp.MONTH_JAN, ntp.Ntp.MONTH_DEC):
                for weekday in range(ntp.Ntp.WEEKDAY_THU, ntp.Ntp.WEEKDAY_SUN + 1):
                    try:
                        result1 = ntp.Ntp.day_from_week_and_weekday(year, month, ntp.Ntp.WEEK_LAST, weekday)
                        result2 = ntp.Ntp.weekday_in_month(year, month, ntp.Ntp.WEEK_LAST, weekday)
                    except:
                        continue

                    if result1 != result2:
                        errors.append(f"For {year}/{month}, day_from_week_and_weekday=>{result1} and weekday_in_month=>{result2}")

        # Raise an assertion with all collected error messages
        self.assertTrue(not errors, "\n".join(errors))


# Run the tests
unittest.TextTestRunner().run(unittest.TestLoader().loadTestsFromTestCase(TestDayFromWeekAndWeekdayWithImport))
```

**Comment by ecwilliams** [comment]
Looking at the code, it looked like it would always work for the last
weekday, and always work for Sunday.  But non-Sunday and non-last could
cause errors depending on the month starting day.

**Comment by ekondayan** [comment]
Not only the last Sundays, but also Thursdays, Fridays and Saturdays. It also works for first weekdays, basically it works for all first and last weekdays. It doesn't work for countries that start DST on the second Sunday, like US, Canada, Greenland, Cuba, etc.

After switching to weekday_in_month() maybe I will mark day_from_week_and_weekday() for deprecation.

P.S.
I found a bug in day_from_week_and_weekday()  that returns wrong first weekdays for certain months, which I fixed in the last commit.

**Comment by ecwilliams** [comment]
I had run into problems with first weekdays, but I made my fork before you
put in your fix.

Yes, deprecating weekday_in_month looks appropriate to me but I didn't want
to make that call.

**Comment by ekondayan** [comment]
Thank you

**Comment by ecwilliams** [comment]
Glad I could help.  Your NTP sync was perfect for my project.

**Pull request merged**
